### ISSUE TITLE
Recursively crawl article from a category

### ISSUE THREAD

**Issue by PierreSelim** [Commonists/SurfaceImageContentGap#8]
It would be nice if the script could recrusively crawl for any article below a category (with a maximum depth probably.)

**Comment by PierreSelim** [comment]
I have committed 034858044f02620b632464316d59db4f844f8773 and b950e8ba42ee0398de122627070c8531b0ef61d2 in order to implement this feature.

I believe it can be marked as closed when we can set the max depth from command line and when we handle exception raised by max recursive call.

**Comment by JeanFred** [comment]
:+1:
